// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: resourceman_nodeman.proto

package resourceman_nodeman

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeManagerTaskResponse_Status int32

const (
	NodeManagerTaskResponse_SUCCESS NodeManagerTaskResponse_Status = 0
	NodeManagerTaskResponse_FAILURE NodeManagerTaskResponse_Status = 1
)

// Enum value maps for NodeManagerTaskResponse_Status.
var (
	NodeManagerTaskResponse_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
	}
	NodeManagerTaskResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"FAILURE": 1,
	}
)

func (x NodeManagerTaskResponse_Status) Enum() *NodeManagerTaskResponse_Status {
	p := new(NodeManagerTaskResponse_Status)
	*p = x
	return p
}

func (x NodeManagerTaskResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeManagerTaskResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_resourceman_nodeman_proto_enumTypes[0].Descriptor()
}

func (NodeManagerTaskResponse_Status) Type() protoreflect.EnumType {
	return &file_resourceman_nodeman_proto_enumTypes[0]
}

func (x NodeManagerTaskResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeManagerTaskResponse_Status.Descriptor instead.
func (NodeManagerTaskResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_resourceman_nodeman_proto_rawDescGZIP(), []int{1, 0}
}

type ResourceManagerTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Task:
	//
	//	*ResourceManagerTaskRequest_Setup_
	//	*ResourceManagerTaskRequest_Fragment_
	//	*ResourceManagerTaskRequest_KeyDistribution_
	//	*ResourceManagerTaskRequest_ReduceTask_
	Task isResourceManagerTaskRequest_Task `protobuf_oneof:"task"`
}

func (x *ResourceManagerTaskRequest) Reset() {
	*x = ResourceManagerTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resourceman_nodeman_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceManagerTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceManagerTaskRequest) ProtoMessage() {}

func (x *ResourceManagerTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceman_nodeman_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceManagerTaskRequest.ProtoReflect.Descriptor instead.
func (*ResourceManagerTaskRequest) Descriptor() ([]byte, []int) {
	return file_resourceman_nodeman_proto_rawDescGZIP(), []int{0}
}

func (m *ResourceManagerTaskRequest) GetTask() isResourceManagerTaskRequest_Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (x *ResourceManagerTaskRequest) GetSetup() *ResourceManagerTaskRequest_Setup {
	if x, ok := x.GetTask().(*ResourceManagerTaskRequest_Setup_); ok {
		return x.Setup
	}
	return nil
}

func (x *ResourceManagerTaskRequest) GetFragment() *ResourceManagerTaskRequest_Fragment {
	if x, ok := x.GetTask().(*ResourceManagerTaskRequest_Fragment_); ok {
		return x.Fragment
	}
	return nil
}

func (x *ResourceManagerTaskRequest) GetKeyDistribution() *ResourceManagerTaskRequest_KeyDistribution {
	if x, ok := x.GetTask().(*ResourceManagerTaskRequest_KeyDistribution_); ok {
		return x.KeyDistribution
	}
	return nil
}

func (x *ResourceManagerTaskRequest) GetReduceTask() *ResourceManagerTaskRequest_ReduceTask {
	if x, ok := x.GetTask().(*ResourceManagerTaskRequest_ReduceTask_); ok {
		return x.ReduceTask
	}
	return nil
}

type isResourceManagerTaskRequest_Task interface {
	isResourceManagerTaskRequest_Task()
}

type ResourceManagerTaskRequest_Setup_ struct {
	Setup *ResourceManagerTaskRequest_Setup `protobuf:"bytes,1,opt,name=setup,proto3,oneof"`
}

type ResourceManagerTaskRequest_Fragment_ struct {
	Fragment *ResourceManagerTaskRequest_Fragment `protobuf:"bytes,2,opt,name=fragment,proto3,oneof"`
}

type ResourceManagerTaskRequest_KeyDistribution_ struct {
	KeyDistribution *ResourceManagerTaskRequest_KeyDistribution `protobuf:"bytes,3,opt,name=keyDistribution,proto3,oneof"`
}

type ResourceManagerTaskRequest_ReduceTask_ struct {
	ReduceTask *ResourceManagerTaskRequest_ReduceTask `protobuf:"bytes,4,opt,name=reduceTask,proto3,oneof"`
}

func (*ResourceManagerTaskRequest_Setup_) isResourceManagerTaskRequest_Task() {}

func (*ResourceManagerTaskRequest_Fragment_) isResourceManagerTaskRequest_Task() {}

func (*ResourceManagerTaskRequest_KeyDistribution_) isResourceManagerTaskRequest_Task() {}

func (*ResourceManagerTaskRequest_ReduceTask_) isResourceManagerTaskRequest_Task() {}

type NodeManagerTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Task:
	//
	//	*NodeManagerTaskResponse_Process_
	//	*NodeManagerTaskResponse_ShuffleComplete_
	//	*NodeManagerTaskResponse_ReduceComplete_
	Task isNodeManagerTaskResponse_Task `protobuf_oneof:"task"`
}

func (x *NodeManagerTaskResponse) Reset() {
	*x = NodeManagerTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resourceman_nodeman_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeManagerTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeManagerTaskResponse) ProtoMessage() {}

func (x *NodeManagerTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resourceman_nodeman_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeManagerTaskResponse.ProtoReflect.Descriptor instead.
func (*NodeManagerTaskResponse) Descriptor() ([]byte, []int) {
	return file_resourceman_nodeman_proto_rawDescGZIP(), []int{1}
}

func (m *NodeManagerTaskResponse) GetTask() isNodeManagerTaskResponse_Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (x *NodeManagerTaskResponse) GetProcess() *NodeManagerTaskResponse_Process {
	if x, ok := x.GetTask().(*NodeManagerTaskResponse_Process_); ok {
		return x.Process
	}
	return nil
}

func (x *NodeManagerTaskResponse) GetShuffleComplete() *NodeManagerTaskResponse_ShuffleComplete {
	if x, ok := x.GetTask().(*NodeManagerTaskResponse_ShuffleComplete_); ok {
		return x.ShuffleComplete
	}
	return nil
}

func (x *NodeManagerTaskResponse) GetReduceComplete() *NodeManagerTaskResponse_ReduceComplete {
	if x, ok := x.GetTask().(*NodeManagerTaskResponse_ReduceComplete_); ok {
		return x.ReduceComplete
	}
	return nil
}

type isNodeManagerTaskResponse_Task interface {
	isNodeManagerTaskResponse_Task()
}

type NodeManagerTaskResponse_Process_ struct {
	Process *NodeManagerTaskResponse_Process `protobuf:"bytes,1,opt,name=process,proto3,oneof"`
}

type NodeManagerTaskResponse_ShuffleComplete_ struct {
	ShuffleComplete *NodeManagerTaskResponse_ShuffleComplete `protobuf:"bytes,2,opt,name=shuffleComplete,proto3,oneof"`
}

type NodeManagerTaskResponse_ReduceComplete_ struct {
	ReduceComplete *NodeManagerTaskResponse_ReduceComplete `protobuf:"bytes,3,opt,name=reduceComplete,proto3,oneof"`
}

func (*NodeManagerTaskResponse_Process_) isNodeManagerTaskResponse_Task() {}

func (*NodeManagerTaskResponse_ShuffleComplete_) isNodeManagerTaskResponse_Task() {}

func (*NodeManagerTaskResponse_ReduceComplete_) isNodeManagerTaskResponse_Task() {}

type ResourceManagerTaskRequest_Fragment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FragmentName string `protobuf:"bytes,1,opt,name=fragmentName,proto3" json:"fragmentName,omitempty"`
	FileName     string `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
}

func (x *ResourceManagerTaskRequest_Fragment) Reset() {
	*x = ResourceManagerTaskRequest_Fragment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resourceman_nodeman_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceManagerTaskRequest_Fragment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceManagerTaskRequest_Fragment) ProtoMessage() {}

func (x *ResourceManagerTaskRequest_Fragment) ProtoReflect() protoreflect.Message {
	mi := &file_resourceman_nodeman_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceManagerTaskRequest_Fragment.ProtoReflect.Descriptor instead.
func (*ResourceManagerTaskRequest_Fragment) Descriptor() ([]byte, []int) {
	return file_resourceman_nodeman_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResourceManagerTaskRequest_Fragment) GetFragmentName() string {
	if x != nil {
		return x.FragmentName
	}
	return ""
}

func (x *ResourceManagerTaskRequest_Fragment) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type ResourceManagerTaskRequest_Setup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Job      []byte `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
}

func (x *ResourceManagerTaskRequest_Setup) Reset() {
	*x = ResourceManagerTaskRequest_Setup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resourceman_nodeman_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceManagerTaskRequest_Setup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceManagerTaskRequest_Setup) ProtoMessage() {}

func (x *ResourceManagerTaskRequest_Setup) ProtoReflect() protoreflect.Message {
	mi := &file_resourceman_nodeman_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceManagerTaskRequest_Setup.ProtoReflect.Descriptor instead.
func (*ResourceManagerTaskRequest_Setup) Descriptor() ([]byte, []int) {
	return file_resourceman_nodeman_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ResourceManagerTaskRequest_Setup) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ResourceManagerTaskRequest_Setup) GetJob() []byte {
	if x != nil {
		return x.Job
	}
	return nil
}

type ResourceManagerTaskRequest_StorageNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID        string  `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Host          string  `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          string  `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	ReduceTaskIDs []int32 `protobuf:"varint,4,rep,packed,name=reduceTaskIDs,proto3" json:"reduceTaskIDs,omitempty"`
}

func (x *ResourceManagerTaskRequest_StorageNode) Reset() {
	*x = ResourceManagerTaskRequest_StorageNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resourceman_nodeman_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceManagerTaskRequest_StorageNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceManagerTaskRequest_StorageNode) ProtoMessage() {}

func (x *ResourceManagerTaskRequest_StorageNode) ProtoReflect() protoreflect.Message {
	mi := &file_resourceman_nodeman_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceManagerTaskRequest_StorageNode.ProtoReflect.Descriptor instead.
func (*ResourceManagerTaskRequest_StorageNode) Descriptor() ([]byte, []int) {
	return file_resourceman_nodeman_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ResourceManagerTaskRequest_StorageNode) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *ResourceManagerTaskRequest_StorageNode) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ResourceManagerTaskRequest_StorageNode) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *ResourceManagerTaskRequest_StorageNode) GetReduceTaskIDs() []int32 {
	if x != nil {
		return x.ReduceTaskIDs
	}
	return nil
}

type ResourceManagerTaskRequest_ReducerKeyDistribution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReducerTaskID int32    `protobuf:"varint,1,opt,name=reducerTaskID,proto3" json:"reducerTaskID,omitempty"`
	Keys          [][]byte `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *ResourceManagerTaskRequest_ReducerKeyDistribution) Reset() {
	*x = ResourceManagerTaskRequest_ReducerKeyDistribution{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resourceman_nodeman_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceManagerTaskRequest_ReducerKeyDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceManagerTaskRequest_ReducerKeyDistribution) ProtoMessage() {}

func (x *ResourceManagerTaskRequest_ReducerKeyDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_resourceman_nodeman_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceManagerTaskRequest_ReducerKeyDistribution.ProtoReflect.Descriptor instead.
func (*ResourceManagerTaskRequest_ReducerKeyDistribution) Descriptor() ([]byte, []int) {
	return file_resourceman_nodeman_proto_rawDescGZIP(), []int{0, 3}
}

func (x *ResourceManagerTaskRequest_ReducerKeyDistribution) GetReducerTaskID() int32 {
	if x != nil {
		return x.ReducerTaskID
	}
	return 0
}

func (x *ResourceManagerTaskRequest_ReducerKeyDistribution) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

type ResourceManagerTaskRequest_KeyDistribution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StorageNode            []*ResourceManagerTaskRequest_StorageNode            `protobuf:"bytes,1,rep,name=storageNode,proto3" json:"storageNode,omitempty"`
	ReducerKeyDistribution []*ResourceManagerTaskRequest_ReducerKeyDistribution `protobuf:"bytes,2,rep,name=reducerKeyDistribution,proto3" json:"reducerKeyDistribution,omitempty"`
}

func (x *ResourceManagerTaskRequest_KeyDistribution) Reset() {
	*x = ResourceManagerTaskRequest_KeyDistribution{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resourceman_nodeman_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceManagerTaskRequest_KeyDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceManagerTaskRequest_KeyDistribution) ProtoMessage() {}

func (x *ResourceManagerTaskRequest_KeyDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_resourceman_nodeman_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceManagerTaskRequest_KeyDistribution.ProtoReflect.Descriptor instead.
func (*ResourceManagerTaskRequest_KeyDistribution) Descriptor() ([]byte, []int) {
	return file_resourceman_nodeman_proto_rawDescGZIP(), []int{0, 4}
}

func (x *ResourceManagerTaskRequest_KeyDistribution) GetStorageNode() []*ResourceManagerTaskRequest_StorageNode {
	if x != nil {
		return x.StorageNode
	}
	return nil
}

func (x *ResourceManagerTaskRequest_KeyDistribution) GetReducerKeyDistribution() []*ResourceManagerTaskRequest_ReducerKeyDistribution {
	if x != nil {
		return x.ReducerKeyDistribution
	}
	return nil
}

type ResourceManagerTaskRequest_ReduceTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskID         []int32 `protobuf:"varint,1,rep,packed,name=taskID,proto3" json:"taskID,omitempty"`
	InputFileName  string  `protobuf:"bytes,2,opt,name=inputFileName,proto3" json:"inputFileName,omitempty"`
	OutputFileName string  `protobuf:"bytes,3,opt,name=outputFileName,proto3" json:"outputFileName,omitempty"`
}

func (x *ResourceManagerTaskRequest_ReduceTask) Reset() {
	*x = ResourceManagerTaskRequest_ReduceTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resourceman_nodeman_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceManagerTaskRequest_ReduceTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceManagerTaskRequest_ReduceTask) ProtoMessage() {}

func (x *ResourceManagerTaskRequest_ReduceTask) ProtoReflect() protoreflect.Message {
	mi := &file_resourceman_nodeman_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceManagerTaskRequest_ReduceTask.ProtoReflect.Descriptor instead.
func (*ResourceManagerTaskRequest_ReduceTask) Descriptor() ([]byte, []int) {
	return file_resourceman_nodeman_proto_rawDescGZIP(), []int{0, 5}
}

func (x *ResourceManagerTaskRequest_ReduceTask) GetTaskID() []int32 {
	if x != nil {
		return x.TaskID
	}
	return nil
}

func (x *ResourceManagerTaskRequest_ReduceTask) GetInputFileName() string {
	if x != nil {
		return x.InputFileName
	}
	return ""
}

func (x *ResourceManagerTaskRequest_ReduceTask) GetOutputFileName() string {
	if x != nil {
		return x.OutputFileName
	}
	return ""
}

type NodeManagerTaskResponse_Process struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       NodeManagerTaskResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=NodeManagerTaskResponse_Status" json:"status,omitempty"`
	FragmentName string                         `protobuf:"bytes,2,opt,name=fragmentName,proto3" json:"fragmentName,omitempty"`
	Keys         [][]byte                       `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *NodeManagerTaskResponse_Process) Reset() {
	*x = NodeManagerTaskResponse_Process{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resourceman_nodeman_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeManagerTaskResponse_Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeManagerTaskResponse_Process) ProtoMessage() {}

func (x *NodeManagerTaskResponse_Process) ProtoReflect() protoreflect.Message {
	mi := &file_resourceman_nodeman_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeManagerTaskResponse_Process.ProtoReflect.Descriptor instead.
func (*NodeManagerTaskResponse_Process) Descriptor() ([]byte, []int) {
	return file_resourceman_nodeman_proto_rawDescGZIP(), []int{1, 0}
}

func (x *NodeManagerTaskResponse_Process) GetStatus() NodeManagerTaskResponse_Status {
	if x != nil {
		return x.Status
	}
	return NodeManagerTaskResponse_SUCCESS
}

func (x *NodeManagerTaskResponse_Process) GetFragmentName() string {
	if x != nil {
		return x.FragmentName
	}
	return ""
}

func (x *NodeManagerTaskResponse_Process) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

type NodeManagerTaskResponse_ShuffleComplete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status NodeManagerTaskResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=NodeManagerTaskResponse_Status" json:"status,omitempty"`
}

func (x *NodeManagerTaskResponse_ShuffleComplete) Reset() {
	*x = NodeManagerTaskResponse_ShuffleComplete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resourceman_nodeman_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeManagerTaskResponse_ShuffleComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeManagerTaskResponse_ShuffleComplete) ProtoMessage() {}

func (x *NodeManagerTaskResponse_ShuffleComplete) ProtoReflect() protoreflect.Message {
	mi := &file_resourceman_nodeman_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeManagerTaskResponse_ShuffleComplete.ProtoReflect.Descriptor instead.
func (*NodeManagerTaskResponse_ShuffleComplete) Descriptor() ([]byte, []int) {
	return file_resourceman_nodeman_proto_rawDescGZIP(), []int{1, 1}
}

func (x *NodeManagerTaskResponse_ShuffleComplete) GetStatus() NodeManagerTaskResponse_Status {
	if x != nil {
		return x.Status
	}
	return NodeManagerTaskResponse_SUCCESS
}

type NodeManagerTaskResponse_ReduceComplete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status NodeManagerTaskResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=NodeManagerTaskResponse_Status" json:"status,omitempty"`
	TaskID int32                          `protobuf:"varint,2,opt,name=taskID,proto3" json:"taskID,omitempty"`
}

func (x *NodeManagerTaskResponse_ReduceComplete) Reset() {
	*x = NodeManagerTaskResponse_ReduceComplete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resourceman_nodeman_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeManagerTaskResponse_ReduceComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeManagerTaskResponse_ReduceComplete) ProtoMessage() {}

func (x *NodeManagerTaskResponse_ReduceComplete) ProtoReflect() protoreflect.Message {
	mi := &file_resourceman_nodeman_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeManagerTaskResponse_ReduceComplete.ProtoReflect.Descriptor instead.
func (*NodeManagerTaskResponse_ReduceComplete) Descriptor() ([]byte, []int) {
	return file_resourceman_nodeman_proto_rawDescGZIP(), []int{1, 2}
}

func (x *NodeManagerTaskResponse_ReduceComplete) GetStatus() NodeManagerTaskResponse_Status {
	if x != nil {
		return x.Status
	}
	return NodeManagerTaskResponse_SUCCESS
}

func (x *NodeManagerTaskResponse_ReduceComplete) GetTaskID() int32 {
	if x != nil {
		return x.TaskID
	}
	return 0
}

var File_resourceman_nodeman_proto protoreflect.FileDescriptor

var file_resourceman_nodeman_proto_rawDesc = []byte{
	0x0a, 0x19, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x6d, 0x61, 0x6e, 0x5f, 0x6e, 0x6f,
	0x64, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd1, 0x07, 0x0a, 0x1a,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x05, 0x73, 0x65,
	0x74, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x75, 0x70, 0x48, 0x00, 0x52, 0x05,
	0x73, 0x65, 0x74, 0x75, 0x70, 0x12, 0x42, 0x0a, 0x08, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52,
	0x08, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x57, 0x0a, 0x0f, 0x6b, 0x65, 0x79,
	0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x4b, 0x65, 0x79, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x00, 0x52, 0x0f, 0x6b, 0x65, 0x79, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x48, 0x0a, 0x0a, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x48, 0x00,
	0x52, 0x0a, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x4a, 0x0a, 0x08,
	0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x72, 0x61, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x35, 0x0a, 0x05, 0x53, 0x65, 0x74, 0x75,
	0x70, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6a, 0x6f, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6a, 0x6f, 0x62, 0x1a,
	0x73, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x24,
	0x0a, 0x0d, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0d, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x54, 0x61, 0x73,
	0x6b, 0x49, 0x44, 0x73, 0x1a, 0x52, 0x0a, 0x16, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x4b,
	0x65, 0x79, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24,
	0x0a, 0x0d, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x54, 0x61,
	0x73, 0x6b, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0c, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x1a, 0xc8, 0x01, 0x0a, 0x0f, 0x4b, 0x65, 0x79,
	0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x49, 0x0a, 0x0b,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x0b, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x6a, 0x0a, 0x16, 0x72, 0x65, 0x64, 0x75, 0x63,
	0x65, 0x72, 0x4b, 0x65, 0x79, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x44,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x16, 0x72, 0x65, 0x64,
	0x75, 0x63, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x1a, 0x72, 0x0a, 0x0a, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x54, 0x61, 0x73,
	0x6b, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x26, 0x0a, 0x0e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22,
	0xd7, 0x04, 0x0a, 0x17, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x07, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x48, 0x00,
	0x52, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x54, 0x0a, 0x0f, 0x73, 0x68, 0x75,
	0x66, 0x66, 0x6c, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x68, 0x75,
	0x66, 0x66, 0x6c, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0f,
	0x73, 0x68, 0x75, 0x66, 0x66, 0x6c, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x51, 0x0a, 0x0e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x48, 0x00, 0x52, 0x0e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x1a, 0x7a, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x37, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x72,
	0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65,
	0x79, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x1a, 0x4a,
	0x0a, 0x0f, 0x53, 0x68, 0x75, 0x66, 0x66, 0x6c, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x61, 0x0a, 0x0e, 0x52, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x37, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x22, 0x22, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45,
	0x53, 0x53, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x10,
	0x01, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x42, 0x20, 0x5a, 0x1e, 0x2e, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x6d, 0x61, 0x6e, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x6d, 0x61, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_resourceman_nodeman_proto_rawDescOnce sync.Once
	file_resourceman_nodeman_proto_rawDescData = file_resourceman_nodeman_proto_rawDesc
)

func file_resourceman_nodeman_proto_rawDescGZIP() []byte {
	file_resourceman_nodeman_proto_rawDescOnce.Do(func() {
		file_resourceman_nodeman_proto_rawDescData = protoimpl.X.CompressGZIP(file_resourceman_nodeman_proto_rawDescData)
	})
	return file_resourceman_nodeman_proto_rawDescData
}

var file_resourceman_nodeman_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_resourceman_nodeman_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_resourceman_nodeman_proto_goTypes = []interface{}{
	(NodeManagerTaskResponse_Status)(0),                       // 0: NodeManagerTaskResponse.Status
	(*ResourceManagerTaskRequest)(nil),                        // 1: ResourceManagerTaskRequest
	(*NodeManagerTaskResponse)(nil),                           // 2: NodeManagerTaskResponse
	(*ResourceManagerTaskRequest_Fragment)(nil),               // 3: ResourceManagerTaskRequest.Fragment
	(*ResourceManagerTaskRequest_Setup)(nil),                  // 4: ResourceManagerTaskRequest.Setup
	(*ResourceManagerTaskRequest_StorageNode)(nil),            // 5: ResourceManagerTaskRequest.StorageNode
	(*ResourceManagerTaskRequest_ReducerKeyDistribution)(nil), // 6: ResourceManagerTaskRequest.ReducerKeyDistribution
	(*ResourceManagerTaskRequest_KeyDistribution)(nil),        // 7: ResourceManagerTaskRequest.KeyDistribution
	(*ResourceManagerTaskRequest_ReduceTask)(nil),             // 8: ResourceManagerTaskRequest.ReduceTask
	(*NodeManagerTaskResponse_Process)(nil),                   // 9: NodeManagerTaskResponse.Process
	(*NodeManagerTaskResponse_ShuffleComplete)(nil),           // 10: NodeManagerTaskResponse.ShuffleComplete
	(*NodeManagerTaskResponse_ReduceComplete)(nil),            // 11: NodeManagerTaskResponse.ReduceComplete
}
var file_resourceman_nodeman_proto_depIdxs = []int32{
	4,  // 0: ResourceManagerTaskRequest.setup:type_name -> ResourceManagerTaskRequest.Setup
	3,  // 1: ResourceManagerTaskRequest.fragment:type_name -> ResourceManagerTaskRequest.Fragment
	7,  // 2: ResourceManagerTaskRequest.keyDistribution:type_name -> ResourceManagerTaskRequest.KeyDistribution
	8,  // 3: ResourceManagerTaskRequest.reduceTask:type_name -> ResourceManagerTaskRequest.ReduceTask
	9,  // 4: NodeManagerTaskResponse.process:type_name -> NodeManagerTaskResponse.Process
	10, // 5: NodeManagerTaskResponse.shuffleComplete:type_name -> NodeManagerTaskResponse.ShuffleComplete
	11, // 6: NodeManagerTaskResponse.reduceComplete:type_name -> NodeManagerTaskResponse.ReduceComplete
	5,  // 7: ResourceManagerTaskRequest.KeyDistribution.storageNode:type_name -> ResourceManagerTaskRequest.StorageNode
	6,  // 8: ResourceManagerTaskRequest.KeyDistribution.reducerKeyDistribution:type_name -> ResourceManagerTaskRequest.ReducerKeyDistribution
	0,  // 9: NodeManagerTaskResponse.Process.status:type_name -> NodeManagerTaskResponse.Status
	0,  // 10: NodeManagerTaskResponse.ShuffleComplete.status:type_name -> NodeManagerTaskResponse.Status
	0,  // 11: NodeManagerTaskResponse.ReduceComplete.status:type_name -> NodeManagerTaskResponse.Status
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_resourceman_nodeman_proto_init() }
func file_resourceman_nodeman_proto_init() {
	if File_resourceman_nodeman_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_resourceman_nodeman_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceManagerTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resourceman_nodeman_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeManagerTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resourceman_nodeman_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceManagerTaskRequest_Fragment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resourceman_nodeman_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceManagerTaskRequest_Setup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resourceman_nodeman_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceManagerTaskRequest_StorageNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resourceman_nodeman_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceManagerTaskRequest_ReducerKeyDistribution); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resourceman_nodeman_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceManagerTaskRequest_KeyDistribution); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resourceman_nodeman_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceManagerTaskRequest_ReduceTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resourceman_nodeman_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeManagerTaskResponse_Process); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resourceman_nodeman_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeManagerTaskResponse_ShuffleComplete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resourceman_nodeman_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeManagerTaskResponse_ReduceComplete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_resourceman_nodeman_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ResourceManagerTaskRequest_Setup_)(nil),
		(*ResourceManagerTaskRequest_Fragment_)(nil),
		(*ResourceManagerTaskRequest_KeyDistribution_)(nil),
		(*ResourceManagerTaskRequest_ReduceTask_)(nil),
	}
	file_resourceman_nodeman_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*NodeManagerTaskResponse_Process_)(nil),
		(*NodeManagerTaskResponse_ShuffleComplete_)(nil),
		(*NodeManagerTaskResponse_ReduceComplete_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resourceman_nodeman_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resourceman_nodeman_proto_goTypes,
		DependencyIndexes: file_resourceman_nodeman_proto_depIdxs,
		EnumInfos:         file_resourceman_nodeman_proto_enumTypes,
		MessageInfos:      file_resourceman_nodeman_proto_msgTypes,
	}.Build()
	File_resourceman_nodeman_proto = out.File
	file_resourceman_nodeman_proto_rawDesc = nil
	file_resourceman_nodeman_proto_goTypes = nil
	file_resourceman_nodeman_proto_depIdxs = nil
}
