// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: client_resourceman.proto

package client_resourceman

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceManagerMessage_ErrorCode int32

const (
	ResourceManagerMessage_NO_ERROR       ResourceManagerMessage_ErrorCode = 0
	ResourceManagerMessage_FILE_NOT_FOUND ResourceManagerMessage_ErrorCode = 1
	ResourceManagerMessage_JOB_NOT_VALID  ResourceManagerMessage_ErrorCode = 2
	ResourceManagerMessage_SERVER_ERROR   ResourceManagerMessage_ErrorCode = 3
)

// Enum value maps for ResourceManagerMessage_ErrorCode.
var (
	ResourceManagerMessage_ErrorCode_name = map[int32]string{
		0: "NO_ERROR",
		1: "FILE_NOT_FOUND",
		2: "JOB_NOT_VALID",
		3: "SERVER_ERROR",
	}
	ResourceManagerMessage_ErrorCode_value = map[string]int32{
		"NO_ERROR":       0,
		"FILE_NOT_FOUND": 1,
		"JOB_NOT_VALID":  2,
		"SERVER_ERROR":   3,
	}
)

func (x ResourceManagerMessage_ErrorCode) Enum() *ResourceManagerMessage_ErrorCode {
	p := new(ResourceManagerMessage_ErrorCode)
	*p = x
	return p
}

func (x ResourceManagerMessage_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceManagerMessage_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_client_resourceman_proto_enumTypes[0].Descriptor()
}

func (ResourceManagerMessage_ErrorCode) Type() protoreflect.EnumType {
	return &file_client_resourceman_proto_enumTypes[0]
}

func (x ResourceManagerMessage_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceManagerMessage_ErrorCode.Descriptor instead.
func (ResourceManagerMessage_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_client_resourceman_proto_rawDescGZIP(), []int{0, 0}
}

type ResourceManagerMessage_ProgressUpdateType int32

const (
	ResourceManagerMessage_JOB_STARTED   ResourceManagerMessage_ProgressUpdateType = 0
	ResourceManagerMessage_JOB_COMPLETED ResourceManagerMessage_ProgressUpdateType = 1
	ResourceManagerMessage_JOB_FAILED    ResourceManagerMessage_ProgressUpdateType = 2
	ResourceManagerMessage_JOB_ONGOING   ResourceManagerMessage_ProgressUpdateType = 3
)

// Enum value maps for ResourceManagerMessage_ProgressUpdateType.
var (
	ResourceManagerMessage_ProgressUpdateType_name = map[int32]string{
		0: "JOB_STARTED",
		1: "JOB_COMPLETED",
		2: "JOB_FAILED",
		3: "JOB_ONGOING",
	}
	ResourceManagerMessage_ProgressUpdateType_value = map[string]int32{
		"JOB_STARTED":   0,
		"JOB_COMPLETED": 1,
		"JOB_FAILED":    2,
		"JOB_ONGOING":   3,
	}
)

func (x ResourceManagerMessage_ProgressUpdateType) Enum() *ResourceManagerMessage_ProgressUpdateType {
	p := new(ResourceManagerMessage_ProgressUpdateType)
	*p = x
	return p
}

func (x ResourceManagerMessage_ProgressUpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceManagerMessage_ProgressUpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_client_resourceman_proto_enumTypes[1].Descriptor()
}

func (ResourceManagerMessage_ProgressUpdateType) Type() protoreflect.EnumType {
	return &file_client_resourceman_proto_enumTypes[1]
}

func (x ResourceManagerMessage_ProgressUpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceManagerMessage_ProgressUpdateType.Descriptor instead.
func (ResourceManagerMessage_ProgressUpdateType) EnumDescriptor() ([]byte, []int) {
	return file_client_resourceman_proto_rawDescGZIP(), []int{0, 1}
}

type ResourceManagerMessage_TaskType int32

const (
	ResourceManagerMessage_MAP    ResourceManagerMessage_TaskType = 0
	ResourceManagerMessage_REDUCE ResourceManagerMessage_TaskType = 1
)

// Enum value maps for ResourceManagerMessage_TaskType.
var (
	ResourceManagerMessage_TaskType_name = map[int32]string{
		0: "MAP",
		1: "REDUCE",
	}
	ResourceManagerMessage_TaskType_value = map[string]int32{
		"MAP":    0,
		"REDUCE": 1,
	}
)

func (x ResourceManagerMessage_TaskType) Enum() *ResourceManagerMessage_TaskType {
	p := new(ResourceManagerMessage_TaskType)
	*p = x
	return p
}

func (x ResourceManagerMessage_TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceManagerMessage_TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_client_resourceman_proto_enumTypes[2].Descriptor()
}

func (ResourceManagerMessage_TaskType) Type() protoreflect.EnumType {
	return &file_client_resourceman_proto_enumTypes[2]
}

func (x ResourceManagerMessage_TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceManagerMessage_TaskType.Descriptor instead.
func (ResourceManagerMessage_TaskType) EnumDescriptor() ([]byte, []int) {
	return file_client_resourceman_proto_rawDescGZIP(), []int{0, 2}
}

type ResourceManagerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*ResourceManagerMessage_JobResponse_
	//	*ResourceManagerMessage_ProgressUpdate_
	Message isResourceManagerMessage_Message `protobuf_oneof:"message"`
}

func (x *ResourceManagerMessage) Reset() {
	*x = ResourceManagerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_resourceman_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceManagerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceManagerMessage) ProtoMessage() {}

func (x *ResourceManagerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_client_resourceman_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceManagerMessage.ProtoReflect.Descriptor instead.
func (*ResourceManagerMessage) Descriptor() ([]byte, []int) {
	return file_client_resourceman_proto_rawDescGZIP(), []int{0}
}

func (m *ResourceManagerMessage) GetMessage() isResourceManagerMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ResourceManagerMessage) GetJobResponse() *ResourceManagerMessage_JobResponse {
	if x, ok := x.GetMessage().(*ResourceManagerMessage_JobResponse_); ok {
		return x.JobResponse
	}
	return nil
}

func (x *ResourceManagerMessage) GetProgressUpdate() *ResourceManagerMessage_ProgressUpdate {
	if x, ok := x.GetMessage().(*ResourceManagerMessage_ProgressUpdate_); ok {
		return x.ProgressUpdate
	}
	return nil
}

type isResourceManagerMessage_Message interface {
	isResourceManagerMessage_Message()
}

type ResourceManagerMessage_JobResponse_ struct {
	JobResponse *ResourceManagerMessage_JobResponse `protobuf:"bytes,1,opt,name=job_response,json=jobResponse,proto3,oneof"`
}

type ResourceManagerMessage_ProgressUpdate_ struct {
	ProgressUpdate *ResourceManagerMessage_ProgressUpdate `protobuf:"bytes,2,opt,name=progress_update,json=progressUpdate,proto3,oneof"`
}

func (*ResourceManagerMessage_JobResponse_) isResourceManagerMessage_Message() {}

func (*ResourceManagerMessage_ProgressUpdate_) isResourceManagerMessage_Message() {}

type ClientJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ClientMessage:
	//
	//	*ClientJobRequest_Jobs_
	ClientMessage isClientJobRequest_ClientMessage `protobuf_oneof:"client_message"`
}

func (x *ClientJobRequest) Reset() {
	*x = ClientJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_resourceman_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientJobRequest) ProtoMessage() {}

func (x *ClientJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_resourceman_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientJobRequest.ProtoReflect.Descriptor instead.
func (*ClientJobRequest) Descriptor() ([]byte, []int) {
	return file_client_resourceman_proto_rawDescGZIP(), []int{1}
}

func (m *ClientJobRequest) GetClientMessage() isClientJobRequest_ClientMessage {
	if m != nil {
		return m.ClientMessage
	}
	return nil
}

func (x *ClientJobRequest) GetJobs() *ClientJobRequest_Jobs {
	if x, ok := x.GetClientMessage().(*ClientJobRequest_Jobs_); ok {
		return x.Jobs
	}
	return nil
}

type isClientJobRequest_ClientMessage interface {
	isClientJobRequest_ClientMessage()
}

type ClientJobRequest_Jobs_ struct {
	Jobs *ClientJobRequest_Jobs `protobuf:"bytes,1,opt,name=jobs,proto3,oneof"`
}

func (*ClientJobRequest_Jobs_) isClientJobRequest_ClientMessage() {}

type ResourceManagerMessage_JobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode ResourceManagerMessage_ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=ResourceManagerMessage_ErrorCode" json:"error_code,omitempty"`
}

func (x *ResourceManagerMessage_JobResponse) Reset() {
	*x = ResourceManagerMessage_JobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_resourceman_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceManagerMessage_JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceManagerMessage_JobResponse) ProtoMessage() {}

func (x *ResourceManagerMessage_JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_resourceman_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceManagerMessage_JobResponse.ProtoReflect.Descriptor instead.
func (*ResourceManagerMessage_JobResponse) Descriptor() ([]byte, []int) {
	return file_client_resourceman_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResourceManagerMessage_JobResponse) GetErrorCode() ResourceManagerMessage_ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ResourceManagerMessage_NO_ERROR
}

type ResourceManagerMessage_TaskProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskType   ResourceManagerMessage_TaskType `protobuf:"varint,1,opt,name=task_type,json=taskType,proto3,enum=ResourceManagerMessage_TaskType" json:"task_type,omitempty"`
	TaskNumber int32                           `protobuf:"varint,2,opt,name=task_number,json=taskNumber,proto3" json:"task_number,omitempty"`
	TotalTasks int32                           `protobuf:"varint,3,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
}

func (x *ResourceManagerMessage_TaskProgress) Reset() {
	*x = ResourceManagerMessage_TaskProgress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_resourceman_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceManagerMessage_TaskProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceManagerMessage_TaskProgress) ProtoMessage() {}

func (x *ResourceManagerMessage_TaskProgress) ProtoReflect() protoreflect.Message {
	mi := &file_client_resourceman_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceManagerMessage_TaskProgress.ProtoReflect.Descriptor instead.
func (*ResourceManagerMessage_TaskProgress) Descriptor() ([]byte, []int) {
	return file_client_resourceman_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ResourceManagerMessage_TaskProgress) GetTaskType() ResourceManagerMessage_TaskType {
	if x != nil {
		return x.TaskType
	}
	return ResourceManagerMessage_MAP
}

func (x *ResourceManagerMessage_TaskProgress) GetTaskNumber() int32 {
	if x != nil {
		return x.TaskNumber
	}
	return 0
}

func (x *ResourceManagerMessage_TaskProgress) GetTotalTasks() int32 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

type ResourceManagerMessage_ProgressUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdateType   ResourceManagerMessage_ProgressUpdateType `protobuf:"varint,1,opt,name=update_type,json=updateType,proto3,enum=ResourceManagerMessage_ProgressUpdateType" json:"update_type,omitempty"`
	TaskProgress *ResourceManagerMessage_TaskProgress      `protobuf:"bytes,2,opt,name=task_progress,json=taskProgress,proto3" json:"task_progress,omitempty"`
}

func (x *ResourceManagerMessage_ProgressUpdate) Reset() {
	*x = ResourceManagerMessage_ProgressUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_resourceman_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceManagerMessage_ProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceManagerMessage_ProgressUpdate) ProtoMessage() {}

func (x *ResourceManagerMessage_ProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_client_resourceman_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceManagerMessage_ProgressUpdate.ProtoReflect.Descriptor instead.
func (*ResourceManagerMessage_ProgressUpdate) Descriptor() ([]byte, []int) {
	return file_client_resourceman_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ResourceManagerMessage_ProgressUpdate) GetUpdateType() ResourceManagerMessage_ProgressUpdateType {
	if x != nil {
		return x.UpdateType
	}
	return ResourceManagerMessage_JOB_STARTED
}

func (x *ResourceManagerMessage_ProgressUpdate) GetTaskProgress() *ResourceManagerMessage_TaskProgress {
	if x != nil {
		return x.TaskProgress
	}
	return nil
}

type ClientJobRequest_Job struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputFileName  string `protobuf:"bytes,1,opt,name=input_file_name,json=inputFileName,proto3" json:"input_file_name,omitempty"`
	OutputFileName string `protobuf:"bytes,2,opt,name=output_file_name,json=outputFileName,proto3" json:"output_file_name,omitempty"`
	ReducerCount   int32  `protobuf:"varint,3,opt,name=reducer_count,json=reducerCount,proto3" json:"reducer_count,omitempty"`
	JobSo          []byte `protobuf:"bytes,4,opt,name=job_so,json=jobSo,proto3" json:"job_so,omitempty"`
}

func (x *ClientJobRequest_Job) Reset() {
	*x = ClientJobRequest_Job{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_resourceman_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientJobRequest_Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientJobRequest_Job) ProtoMessage() {}

func (x *ClientJobRequest_Job) ProtoReflect() protoreflect.Message {
	mi := &file_client_resourceman_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientJobRequest_Job.ProtoReflect.Descriptor instead.
func (*ClientJobRequest_Job) Descriptor() ([]byte, []int) {
	return file_client_resourceman_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ClientJobRequest_Job) GetInputFileName() string {
	if x != nil {
		return x.InputFileName
	}
	return ""
}

func (x *ClientJobRequest_Job) GetOutputFileName() string {
	if x != nil {
		return x.OutputFileName
	}
	return ""
}

func (x *ClientJobRequest_Job) GetReducerCount() int32 {
	if x != nil {
		return x.ReducerCount
	}
	return 0
}

func (x *ClientJobRequest_Job) GetJobSo() []byte {
	if x != nil {
		return x.JobSo
	}
	return nil
}

type ClientJobRequest_Jobs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jobs []*ClientJobRequest_Job `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
}

func (x *ClientJobRequest_Jobs) Reset() {
	*x = ClientJobRequest_Jobs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_resourceman_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientJobRequest_Jobs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientJobRequest_Jobs) ProtoMessage() {}

func (x *ClientJobRequest_Jobs) ProtoReflect() protoreflect.Message {
	mi := &file_client_resourceman_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientJobRequest_Jobs.ProtoReflect.Descriptor instead.
func (*ClientJobRequest_Jobs) Descriptor() ([]byte, []int) {
	return file_client_resourceman_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ClientJobRequest_Jobs) GetJobs() []*ClientJobRequest_Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

var File_client_resourceman_proto protoreflect.FileDescriptor

var file_client_resourceman_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9e, 0x06, 0x0a, 0x16, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x48, 0x0a, 0x0c, 0x6a, 0x6f, 0x62, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x0b, 0x6a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x51, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x48, 0x00, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x1a, 0x4f, 0x0a, 0x0b, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x40, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x1a, 0x8f, 0x01, 0x0a, 0x0c, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x72, 0x6f, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x3d, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x61, 0x73, 0x6b, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x74, 0x61,
	0x73, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x54, 0x61, 0x73, 0x6b, 0x73, 0x1a, 0xa8, 0x01, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x4b, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x49, 0x0a, 0x0d, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x70, 0x72,
	0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x52, 0x0c, 0x74, 0x61, 0x73, 0x6b, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x22, 0x52, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0c, 0x0a,
	0x08, 0x4e, 0x4f, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x46,
	0x49, 0x4c, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x01, 0x12,
	0x11, 0x0a, 0x0d, 0x4a, 0x4f, 0x42, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x56, 0x41, 0x4c, 0x49, 0x44,
	0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x03, 0x22, 0x59, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x4a, 0x4f,
	0x42, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x4a,
	0x4f, 0x42, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0e,
	0x0a, 0x0a, 0x4a, 0x4f, 0x42, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0f,
	0x0a, 0x0b, 0x4a, 0x4f, 0x42, 0x5f, 0x4f, 0x4e, 0x47, 0x4f, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x22,
	0x1f, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x4d,
	0x41, 0x50, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x44, 0x55, 0x43, 0x45, 0x10, 0x01,
	0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x9b, 0x02, 0x0a, 0x10,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2c, 0x0a, 0x04, 0x6a, 0x6f, 0x62, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x4a, 0x6f, 0x62, 0x73, 0x48, 0x00, 0x52, 0x04, 0x6a, 0x6f, 0x62, 0x73, 0x1a, 0x93,
	0x01, 0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f,
	0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28,
	0x0a, 0x10, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x64, 0x75,
	0x63, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x73, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6a,
	0x6f, 0x62, 0x53, 0x6f, 0x1a, 0x31, 0x0a, 0x04, 0x4a, 0x6f, 0x62, 0x73, 0x12, 0x29, 0x0a, 0x04,
	0x6a, 0x6f, 0x62, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4a, 0x6f,
	0x62, 0x52, 0x04, 0x6a, 0x6f, 0x62, 0x73, 0x42, 0x10, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x1f, 0x5a, 0x1d, 0x2e, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x6d, 0x61, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_client_resourceman_proto_rawDescOnce sync.Once
	file_client_resourceman_proto_rawDescData = file_client_resourceman_proto_rawDesc
)

func file_client_resourceman_proto_rawDescGZIP() []byte {
	file_client_resourceman_proto_rawDescOnce.Do(func() {
		file_client_resourceman_proto_rawDescData = protoimpl.X.CompressGZIP(file_client_resourceman_proto_rawDescData)
	})
	return file_client_resourceman_proto_rawDescData
}

var file_client_resourceman_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_client_resourceman_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_client_resourceman_proto_goTypes = []interface{}{
	(ResourceManagerMessage_ErrorCode)(0),          // 0: ResourceManagerMessage.ErrorCode
	(ResourceManagerMessage_ProgressUpdateType)(0), // 1: ResourceManagerMessage.ProgressUpdateType
	(ResourceManagerMessage_TaskType)(0),           // 2: ResourceManagerMessage.TaskType
	(*ResourceManagerMessage)(nil),                 // 3: ResourceManagerMessage
	(*ClientJobRequest)(nil),                       // 4: ClientJobRequest
	(*ResourceManagerMessage_JobResponse)(nil),     // 5: ResourceManagerMessage.JobResponse
	(*ResourceManagerMessage_TaskProgress)(nil),    // 6: ResourceManagerMessage.TaskProgress
	(*ResourceManagerMessage_ProgressUpdate)(nil),  // 7: ResourceManagerMessage.ProgressUpdate
	(*ClientJobRequest_Job)(nil),                   // 8: ClientJobRequest.Job
	(*ClientJobRequest_Jobs)(nil),                  // 9: ClientJobRequest.Jobs
}
var file_client_resourceman_proto_depIdxs = []int32{
	5, // 0: ResourceManagerMessage.job_response:type_name -> ResourceManagerMessage.JobResponse
	7, // 1: ResourceManagerMessage.progress_update:type_name -> ResourceManagerMessage.ProgressUpdate
	9, // 2: ClientJobRequest.jobs:type_name -> ClientJobRequest.Jobs
	0, // 3: ResourceManagerMessage.JobResponse.error_code:type_name -> ResourceManagerMessage.ErrorCode
	2, // 4: ResourceManagerMessage.TaskProgress.task_type:type_name -> ResourceManagerMessage.TaskType
	1, // 5: ResourceManagerMessage.ProgressUpdate.update_type:type_name -> ResourceManagerMessage.ProgressUpdateType
	6, // 6: ResourceManagerMessage.ProgressUpdate.task_progress:type_name -> ResourceManagerMessage.TaskProgress
	8, // 7: ClientJobRequest.Jobs.jobs:type_name -> ClientJobRequest.Job
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_client_resourceman_proto_init() }
func file_client_resourceman_proto_init() {
	if File_client_resourceman_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_client_resourceman_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceManagerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_resourceman_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_resourceman_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceManagerMessage_JobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_resourceman_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceManagerMessage_TaskProgress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_resourceman_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceManagerMessage_ProgressUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_resourceman_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientJobRequest_Job); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_resourceman_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientJobRequest_Jobs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_client_resourceman_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ResourceManagerMessage_JobResponse_)(nil),
		(*ResourceManagerMessage_ProgressUpdate_)(nil),
	}
	file_client_resourceman_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ClientJobRequest_Jobs_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_client_resourceman_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_resourceman_proto_goTypes,
		DependencyIndexes: file_client_resourceman_proto_depIdxs,
		EnumInfos:         file_client_resourceman_proto_enumTypes,
		MessageInfos:      file_client_resourceman_proto_msgTypes,
	}.Build()
	File_client_resourceman_proto = out.File
	file_client_resourceman_proto_rawDesc = nil
	file_client_resourceman_proto_goTypes = nil
	file_client_resourceman_proto_depIdxs = nil
}
