// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: resourceman_controller.proto

package resourceman_controller

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControllerResponse_ErrorCode int32

const (
	ControllerResponse_NO_ERROR       ControllerResponse_ErrorCode = 0
	ControllerResponse_FILE_NOT_FOUND ControllerResponse_ErrorCode = 1
	ControllerResponse_SERVER_ERROR   ControllerResponse_ErrorCode = 3
)

// Enum value maps for ControllerResponse_ErrorCode.
var (
	ControllerResponse_ErrorCode_name = map[int32]string{
		0: "NO_ERROR",
		1: "FILE_NOT_FOUND",
		3: "SERVER_ERROR",
	}
	ControllerResponse_ErrorCode_value = map[string]int32{
		"NO_ERROR":       0,
		"FILE_NOT_FOUND": 1,
		"SERVER_ERROR":   3,
	}
)

func (x ControllerResponse_ErrorCode) Enum() *ControllerResponse_ErrorCode {
	p := new(ControllerResponse_ErrorCode)
	*p = x
	return p
}

func (x ControllerResponse_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControllerResponse_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_resourceman_controller_proto_enumTypes[0].Descriptor()
}

func (ControllerResponse_ErrorCode) Type() protoreflect.EnumType {
	return &file_resourceman_controller_proto_enumTypes[0]
}

func (x ControllerResponse_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControllerResponse_ErrorCode.Descriptor instead.
func (ControllerResponse_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_resourceman_controller_proto_rawDescGZIP(), []int{1, 0}
}

type ResourceManagerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*ResourceManagerRequest_LayoutRequest_
	Message isResourceManagerRequest_Message `protobuf_oneof:"message"`
}

func (x *ResourceManagerRequest) Reset() {
	*x = ResourceManagerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resourceman_controller_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceManagerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceManagerRequest) ProtoMessage() {}

func (x *ResourceManagerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceman_controller_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceManagerRequest.ProtoReflect.Descriptor instead.
func (*ResourceManagerRequest) Descriptor() ([]byte, []int) {
	return file_resourceman_controller_proto_rawDescGZIP(), []int{0}
}

func (m *ResourceManagerRequest) GetMessage() isResourceManagerRequest_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ResourceManagerRequest) GetLayoutRequest() *ResourceManagerRequest_LayoutRequest {
	if x, ok := x.GetMessage().(*ResourceManagerRequest_LayoutRequest_); ok {
		return x.LayoutRequest
	}
	return nil
}

type isResourceManagerRequest_Message interface {
	isResourceManagerRequest_Message()
}

type ResourceManagerRequest_LayoutRequest_ struct {
	LayoutRequest *ResourceManagerRequest_LayoutRequest `protobuf:"bytes,1,opt,name=layout_request,json=layoutRequest,proto3,oneof"`
}

func (*ResourceManagerRequest_LayoutRequest_) isResourceManagerRequest_Message() {}

type ControllerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ControllerMessage:
	//
	//	*ControllerResponse_FragLayoutResponse_
	ControllerMessage isControllerResponse_ControllerMessage `protobuf_oneof:"controller_message"`
}

func (x *ControllerResponse) Reset() {
	*x = ControllerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resourceman_controller_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControllerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerResponse) ProtoMessage() {}

func (x *ControllerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resourceman_controller_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerResponse.ProtoReflect.Descriptor instead.
func (*ControllerResponse) Descriptor() ([]byte, []int) {
	return file_resourceman_controller_proto_rawDescGZIP(), []int{1}
}

func (m *ControllerResponse) GetControllerMessage() isControllerResponse_ControllerMessage {
	if m != nil {
		return m.ControllerMessage
	}
	return nil
}

func (x *ControllerResponse) GetFragLayoutResponse() *ControllerResponse_FragLayoutResponse {
	if x, ok := x.GetControllerMessage().(*ControllerResponse_FragLayoutResponse_); ok {
		return x.FragLayoutResponse
	}
	return nil
}

type isControllerResponse_ControllerMessage interface {
	isControllerResponse_ControllerMessage()
}

type ControllerResponse_FragLayoutResponse_ struct {
	FragLayoutResponse *ControllerResponse_FragLayoutResponse `protobuf:"bytes,1,opt,name=frag_layout_response,json=fragLayoutResponse,proto3,oneof"`
}

func (*ControllerResponse_FragLayoutResponse_) isControllerResponse_ControllerMessage() {}

type ResourceManagerRequest_LayoutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *ResourceManagerRequest_LayoutRequest) Reset() {
	*x = ResourceManagerRequest_LayoutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resourceman_controller_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceManagerRequest_LayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceManagerRequest_LayoutRequest) ProtoMessage() {}

func (x *ResourceManagerRequest_LayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceman_controller_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceManagerRequest_LayoutRequest.ProtoReflect.Descriptor instead.
func (*ResourceManagerRequest_LayoutRequest) Descriptor() ([]byte, []int) {
	return file_resourceman_controller_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResourceManagerRequest_LayoutRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type ControllerResponse_FragLayoutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode         ControllerResponse_ErrorCode                          `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=ControllerResponse_ErrorCode" json:"error_code,omitempty"`
	TotalNumFragments uint32                                                `protobuf:"varint,2,opt,name=total_num_fragments,json=totalNumFragments,proto3" json:"total_num_fragments,omitempty"`
	FragmentLayout    []*ControllerResponse_FragLayoutResponse_FragmentInfo `protobuf:"bytes,5,rep,name=fragment_layout,json=fragmentLayout,proto3" json:"fragment_layout,omitempty"`
}

func (x *ControllerResponse_FragLayoutResponse) Reset() {
	*x = ControllerResponse_FragLayoutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resourceman_controller_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControllerResponse_FragLayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerResponse_FragLayoutResponse) ProtoMessage() {}

func (x *ControllerResponse_FragLayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resourceman_controller_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerResponse_FragLayoutResponse.ProtoReflect.Descriptor instead.
func (*ControllerResponse_FragLayoutResponse) Descriptor() ([]byte, []int) {
	return file_resourceman_controller_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ControllerResponse_FragLayoutResponse) GetErrorCode() ControllerResponse_ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ControllerResponse_NO_ERROR
}

func (x *ControllerResponse_FragLayoutResponse) GetTotalNumFragments() uint32 {
	if x != nil {
		return x.TotalNumFragments
	}
	return 0
}

func (x *ControllerResponse_FragLayoutResponse) GetFragmentLayout() []*ControllerResponse_FragLayoutResponse_FragmentInfo {
	if x != nil {
		return x.FragmentLayout
	}
	return nil
}

type ControllerResponse_FragLayoutResponse_StorageNodeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StorageNodeId string `protobuf:"bytes,1,opt,name=storage_node_id,json=storageNodeId,proto3" json:"storage_node_id,omitempty"`
	Host          string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          string `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *ControllerResponse_FragLayoutResponse_StorageNodeInfo) Reset() {
	*x = ControllerResponse_FragLayoutResponse_StorageNodeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resourceman_controller_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControllerResponse_FragLayoutResponse_StorageNodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerResponse_FragLayoutResponse_StorageNodeInfo) ProtoMessage() {}

func (x *ControllerResponse_FragLayoutResponse_StorageNodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_resourceman_controller_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerResponse_FragLayoutResponse_StorageNodeInfo.ProtoReflect.Descriptor instead.
func (*ControllerResponse_FragLayoutResponse_StorageNodeInfo) Descriptor() ([]byte, []int) {
	return file_resourceman_controller_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *ControllerResponse_FragLayoutResponse_StorageNodeInfo) GetStorageNodeId() string {
	if x != nil {
		return x.StorageNodeId
	}
	return ""
}

func (x *ControllerResponse_FragLayoutResponse_StorageNodeInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ControllerResponse_FragLayoutResponse_StorageNodeInfo) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type ControllerResponse_FragLayoutResponse_FragmentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FragmentId     string                                                   `protobuf:"bytes,1,opt,name=fragment_id,json=fragmentId,proto3" json:"fragment_id,omitempty"`
	Size           int64                                                    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	StorageNodeIds []*ControllerResponse_FragLayoutResponse_StorageNodeInfo `protobuf:"bytes,3,rep,name=storage_node_ids,json=storageNodeIds,proto3" json:"storage_node_ids,omitempty"`
}

func (x *ControllerResponse_FragLayoutResponse_FragmentInfo) Reset() {
	*x = ControllerResponse_FragLayoutResponse_FragmentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resourceman_controller_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControllerResponse_FragLayoutResponse_FragmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerResponse_FragLayoutResponse_FragmentInfo) ProtoMessage() {}

func (x *ControllerResponse_FragLayoutResponse_FragmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_resourceman_controller_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerResponse_FragLayoutResponse_FragmentInfo.ProtoReflect.Descriptor instead.
func (*ControllerResponse_FragLayoutResponse_FragmentInfo) Descriptor() ([]byte, []int) {
	return file_resourceman_controller_proto_rawDescGZIP(), []int{1, 0, 1}
}

func (x *ControllerResponse_FragLayoutResponse_FragmentInfo) GetFragmentId() string {
	if x != nil {
		return x.FragmentId
	}
	return ""
}

func (x *ControllerResponse_FragLayoutResponse_FragmentInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ControllerResponse_FragLayoutResponse_FragmentInfo) GetStorageNodeIds() []*ControllerResponse_FragLayoutResponse_StorageNodeInfo {
	if x != nil {
		return x.StorageNodeIds
	}
	return nil
}

var File_resourceman_controller_proto protoreflect.FileDescriptor

var file_resourceman_controller_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x6d, 0x61, 0x6e, 0x5f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa1,
	0x01, 0x0a, 0x16, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4e, 0x0a, 0x0e, 0x6c, 0x61, 0x79,
	0x6f, 0x75, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x25, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x6c, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x0a, 0x0d, 0x4c, 0x61, 0x79,
	0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0xb5, 0x05, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x14, 0x66, 0x72, 0x61,
	0x67, 0x5f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x72, 0x61,
	0x67, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x00, 0x52, 0x12, 0x66, 0x72, 0x61, 0x67, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0xeb, 0x03, 0x0a, 0x12, 0x46, 0x72, 0x61, 0x67, 0x4c, 0x61,
	0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0a,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1d, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x5f, 0x6e, 0x75, 0x6d, 0x5f, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75,
	0x6d, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x5c, 0x0a, 0x0f, 0x66, 0x72,
	0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x72, 0x61, 0x67, 0x4c, 0x61, 0x79,
	0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x72, 0x61, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x1a, 0x61, 0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x0f, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64,
	0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x1a, 0xa5, 0x01, 0x0a, 0x0c,
	0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0b,
	0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x12, 0x60, 0x0a, 0x10, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x46, 0x72, 0x61, 0x67, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x49, 0x64, 0x73, 0x22, 0x3f, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x12,
	0x0a, 0x0e, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44,
	0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x03, 0x42, 0x14, 0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x23, 0x5a, 0x21, 0x2e, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x6d, 0x61, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_resourceman_controller_proto_rawDescOnce sync.Once
	file_resourceman_controller_proto_rawDescData = file_resourceman_controller_proto_rawDesc
)

func file_resourceman_controller_proto_rawDescGZIP() []byte {
	file_resourceman_controller_proto_rawDescOnce.Do(func() {
		file_resourceman_controller_proto_rawDescData = protoimpl.X.CompressGZIP(file_resourceman_controller_proto_rawDescData)
	})
	return file_resourceman_controller_proto_rawDescData
}

var file_resourceman_controller_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_resourceman_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_resourceman_controller_proto_goTypes = []interface{}{
	(ControllerResponse_ErrorCode)(0),                             // 0: ControllerResponse.ErrorCode
	(*ResourceManagerRequest)(nil),                                // 1: ResourceManagerRequest
	(*ControllerResponse)(nil),                                    // 2: ControllerResponse
	(*ResourceManagerRequest_LayoutRequest)(nil),                  // 3: ResourceManagerRequest.LayoutRequest
	(*ControllerResponse_FragLayoutResponse)(nil),                 // 4: ControllerResponse.FragLayoutResponse
	(*ControllerResponse_FragLayoutResponse_StorageNodeInfo)(nil), // 5: ControllerResponse.FragLayoutResponse.StorageNodeInfo
	(*ControllerResponse_FragLayoutResponse_FragmentInfo)(nil),    // 6: ControllerResponse.FragLayoutResponse.FragmentInfo
}
var file_resourceman_controller_proto_depIdxs = []int32{
	3, // 0: ResourceManagerRequest.layout_request:type_name -> ResourceManagerRequest.LayoutRequest
	4, // 1: ControllerResponse.frag_layout_response:type_name -> ControllerResponse.FragLayoutResponse
	0, // 2: ControllerResponse.FragLayoutResponse.error_code:type_name -> ControllerResponse.ErrorCode
	6, // 3: ControllerResponse.FragLayoutResponse.fragment_layout:type_name -> ControllerResponse.FragLayoutResponse.FragmentInfo
	5, // 4: ControllerResponse.FragLayoutResponse.FragmentInfo.storage_node_ids:type_name -> ControllerResponse.FragLayoutResponse.StorageNodeInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_resourceman_controller_proto_init() }
func file_resourceman_controller_proto_init() {
	if File_resourceman_controller_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_resourceman_controller_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceManagerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resourceman_controller_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControllerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resourceman_controller_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceManagerRequest_LayoutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resourceman_controller_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControllerResponse_FragLayoutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resourceman_controller_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControllerResponse_FragLayoutResponse_StorageNodeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resourceman_controller_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControllerResponse_FragLayoutResponse_FragmentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_resourceman_controller_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ResourceManagerRequest_LayoutRequest_)(nil),
	}
	file_resourceman_controller_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ControllerResponse_FragLayoutResponse_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resourceman_controller_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resourceman_controller_proto_goTypes,
		DependencyIndexes: file_resourceman_controller_proto_depIdxs,
		EnumInfos:         file_resourceman_controller_proto_enumTypes,
		MessageInfos:      file_resourceman_controller_proto_msgTypes,
	}.Build()
	File_resourceman_controller_proto = out.File
	file_resourceman_controller_proto_rawDesc = nil
	file_resourceman_controller_proto_goTypes = nil
	file_resourceman_controller_proto_depIdxs = nil
}
