// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: controller_client.proto

package controller_client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControllerMessage_StatusCode int32

const (
	ControllerMessage_OK                  ControllerMessage_StatusCode = 0
	ControllerMessage_ERROR               ControllerMessage_StatusCode = 1
	ControllerMessage_FILE_NOT_FOUND      ControllerMessage_StatusCode = 2
	ControllerMessage_FILE_ALREADY_EXISTS ControllerMessage_StatusCode = 3
	ControllerMessage_FILE_TOO_LARGE      ControllerMessage_StatusCode = 4
)

// Enum value maps for ControllerMessage_StatusCode.
var (
	ControllerMessage_StatusCode_name = map[int32]string{
		0: "OK",
		1: "ERROR",
		2: "FILE_NOT_FOUND",
		3: "FILE_ALREADY_EXISTS",
		4: "FILE_TOO_LARGE",
	}
	ControllerMessage_StatusCode_value = map[string]int32{
		"OK":                  0,
		"ERROR":               1,
		"FILE_NOT_FOUND":      2,
		"FILE_ALREADY_EXISTS": 3,
		"FILE_TOO_LARGE":      4,
	}
)

func (x ControllerMessage_StatusCode) Enum() *ControllerMessage_StatusCode {
	p := new(ControllerMessage_StatusCode)
	*p = x
	return p
}

func (x ControllerMessage_StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControllerMessage_StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_controller_client_proto_enumTypes[0].Descriptor()
}

func (ControllerMessage_StatusCode) Type() protoreflect.EnumType {
	return &file_controller_client_proto_enumTypes[0]
}

func (x ControllerMessage_StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControllerMessage_StatusCode.Descriptor instead.
func (ControllerMessage_StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_controller_client_proto_rawDescGZIP(), []int{0, 0}
}

type ClientMessage_RestOption int32

const (
	ClientMessage_GET    ClientMessage_RestOption = 0
	ClientMessage_PUT    ClientMessage_RestOption = 1
	ClientMessage_DELETE ClientMessage_RestOption = 2
	ClientMessage_LS     ClientMessage_RestOption = 3
)

// Enum value maps for ClientMessage_RestOption.
var (
	ClientMessage_RestOption_name = map[int32]string{
		0: "GET",
		1: "PUT",
		2: "DELETE",
		3: "LS",
	}
	ClientMessage_RestOption_value = map[string]int32{
		"GET":    0,
		"PUT":    1,
		"DELETE": 2,
		"LS":     3,
	}
)

func (x ClientMessage_RestOption) Enum() *ClientMessage_RestOption {
	p := new(ClientMessage_RestOption)
	*p = x
	return p
}

func (x ClientMessage_RestOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientMessage_RestOption) Descriptor() protoreflect.EnumDescriptor {
	return file_controller_client_proto_enumTypes[1].Descriptor()
}

func (ClientMessage_RestOption) Type() protoreflect.EnumType {
	return &file_controller_client_proto_enumTypes[1]
}

func (x ClientMessage_RestOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientMessage_RestOption.Descriptor instead.
func (ClientMessage_RestOption) EnumDescriptor() ([]byte, []int) {
	return file_controller_client_proto_rawDescGZIP(), []int{1, 0}
}

type ControllerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ControllerMessage:
	//
	//	*ControllerMessage_PlanResponse_
	//	*ControllerMessage_FragLayoutResponse_
	//	*ControllerMessage_DeleteResponse_
	//	*ControllerMessage_LsResponse_
	ControllerMessage isControllerMessage_ControllerMessage `protobuf_oneof:"controller_message"`
}

func (x *ControllerMessage) Reset() {
	*x = ControllerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControllerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage) ProtoMessage() {}

func (x *ControllerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_controller_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage.ProtoReflect.Descriptor instead.
func (*ControllerMessage) Descriptor() ([]byte, []int) {
	return file_controller_client_proto_rawDescGZIP(), []int{0}
}

func (m *ControllerMessage) GetControllerMessage() isControllerMessage_ControllerMessage {
	if m != nil {
		return m.ControllerMessage
	}
	return nil
}

func (x *ControllerMessage) GetPlanResponse() *ControllerMessage_PlanResponse {
	if x, ok := x.GetControllerMessage().(*ControllerMessage_PlanResponse_); ok {
		return x.PlanResponse
	}
	return nil
}

func (x *ControllerMessage) GetFragLayoutResponse() *ControllerMessage_FragLayoutResponse {
	if x, ok := x.GetControllerMessage().(*ControllerMessage_FragLayoutResponse_); ok {
		return x.FragLayoutResponse
	}
	return nil
}

func (x *ControllerMessage) GetDeleteResponse() *ControllerMessage_DeleteResponse {
	if x, ok := x.GetControllerMessage().(*ControllerMessage_DeleteResponse_); ok {
		return x.DeleteResponse
	}
	return nil
}

func (x *ControllerMessage) GetLsResponse() *ControllerMessage_LsResponse {
	if x, ok := x.GetControllerMessage().(*ControllerMessage_LsResponse_); ok {
		return x.LsResponse
	}
	return nil
}

type isControllerMessage_ControllerMessage interface {
	isControllerMessage_ControllerMessage()
}

type ControllerMessage_PlanResponse_ struct {
	PlanResponse *ControllerMessage_PlanResponse `protobuf:"bytes,1,opt,name=plan_response,json=planResponse,proto3,oneof"`
}

type ControllerMessage_FragLayoutResponse_ struct {
	FragLayoutResponse *ControllerMessage_FragLayoutResponse `protobuf:"bytes,2,opt,name=frag_layout_response,json=fragLayoutResponse,proto3,oneof"`
}

type ControllerMessage_DeleteResponse_ struct {
	DeleteResponse *ControllerMessage_DeleteResponse `protobuf:"bytes,3,opt,name=delete_response,json=deleteResponse,proto3,oneof"`
}

type ControllerMessage_LsResponse_ struct {
	LsResponse *ControllerMessage_LsResponse `protobuf:"bytes,4,opt,name=ls_response,json=lsResponse,proto3,oneof"`
}

func (*ControllerMessage_PlanResponse_) isControllerMessage_ControllerMessage() {}

func (*ControllerMessage_FragLayoutResponse_) isControllerMessage_ControllerMessage() {}

func (*ControllerMessage_DeleteResponse_) isControllerMessage_ControllerMessage() {}

func (*ControllerMessage_LsResponse_) isControllerMessage_ControllerMessage() {}

type ClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ClientMessage:
	//
	//	*ClientMessage_PutRequest_
	//	*ClientMessage_GetRequest_
	//	*ClientMessage_DeleteRequest_
	//	*ClientMessage_LsRequest_
	ClientMessage isClientMessage_ClientMessage `protobuf_oneof:"client_message"`
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_controller_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_controller_client_proto_rawDescGZIP(), []int{1}
}

func (m *ClientMessage) GetClientMessage() isClientMessage_ClientMessage {
	if m != nil {
		return m.ClientMessage
	}
	return nil
}

func (x *ClientMessage) GetPutRequest() *ClientMessage_PutRequest {
	if x, ok := x.GetClientMessage().(*ClientMessage_PutRequest_); ok {
		return x.PutRequest
	}
	return nil
}

func (x *ClientMessage) GetGetRequest() *ClientMessage_GetRequest {
	if x, ok := x.GetClientMessage().(*ClientMessage_GetRequest_); ok {
		return x.GetRequest
	}
	return nil
}

func (x *ClientMessage) GetDeleteRequest() *ClientMessage_DeleteRequest {
	if x, ok := x.GetClientMessage().(*ClientMessage_DeleteRequest_); ok {
		return x.DeleteRequest
	}
	return nil
}

func (x *ClientMessage) GetLsRequest() *ClientMessage_LsRequest {
	if x, ok := x.GetClientMessage().(*ClientMessage_LsRequest_); ok {
		return x.LsRequest
	}
	return nil
}

type isClientMessage_ClientMessage interface {
	isClientMessage_ClientMessage()
}

type ClientMessage_PutRequest_ struct {
	PutRequest *ClientMessage_PutRequest `protobuf:"bytes,1,opt,name=put_request,json=putRequest,proto3,oneof"`
}

type ClientMessage_GetRequest_ struct {
	GetRequest *ClientMessage_GetRequest `protobuf:"bytes,2,opt,name=get_request,json=getRequest,proto3,oneof"`
}

type ClientMessage_DeleteRequest_ struct {
	DeleteRequest *ClientMessage_DeleteRequest `protobuf:"bytes,3,opt,name=delete_request,json=deleteRequest,proto3,oneof"`
}

type ClientMessage_LsRequest_ struct {
	LsRequest *ClientMessage_LsRequest `protobuf:"bytes,4,opt,name=ls_request,json=lsRequest,proto3,oneof"`
}

func (*ClientMessage_PutRequest_) isClientMessage_ClientMessage() {}

func (*ClientMessage_GetRequest_) isClientMessage_ClientMessage() {}

func (*ClientMessage_DeleteRequest_) isClientMessage_ClientMessage() {}

func (*ClientMessage_LsRequest_) isClientMessage_ClientMessage() {}

type ControllerMessage_PlanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode        ControllerMessage_StatusCode                   `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=ControllerMessage_StatusCode" json:"status_code,omitempty"`
	TotalNumFragments uint32                                         `protobuf:"varint,2,opt,name=total_num_fragments,json=totalNumFragments,proto3" json:"total_num_fragments,omitempty"`
	FragmentLayout    []*ControllerMessage_PlanResponse_FragmentInfo `protobuf:"bytes,5,rep,name=fragment_layout,json=fragmentLayout,proto3" json:"fragment_layout,omitempty"`
}

func (x *ControllerMessage_PlanResponse) Reset() {
	*x = ControllerMessage_PlanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_client_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControllerMessage_PlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage_PlanResponse) ProtoMessage() {}

func (x *ControllerMessage_PlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_client_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage_PlanResponse.ProtoReflect.Descriptor instead.
func (*ControllerMessage_PlanResponse) Descriptor() ([]byte, []int) {
	return file_controller_client_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ControllerMessage_PlanResponse) GetStatusCode() ControllerMessage_StatusCode {
	if x != nil {
		return x.StatusCode
	}
	return ControllerMessage_OK
}

func (x *ControllerMessage_PlanResponse) GetTotalNumFragments() uint32 {
	if x != nil {
		return x.TotalNumFragments
	}
	return 0
}

func (x *ControllerMessage_PlanResponse) GetFragmentLayout() []*ControllerMessage_PlanResponse_FragmentInfo {
	if x != nil {
		return x.FragmentLayout
	}
	return nil
}

type ControllerMessage_FragLayoutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode        ControllerMessage_StatusCode                         `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=ControllerMessage_StatusCode" json:"status_code,omitempty"`
	TotalNumFragments uint32                                               `protobuf:"varint,2,opt,name=total_num_fragments,json=totalNumFragments,proto3" json:"total_num_fragments,omitempty"`
	FragmentLayout    []*ControllerMessage_FragLayoutResponse_FragmentInfo `protobuf:"bytes,5,rep,name=fragment_layout,json=fragmentLayout,proto3" json:"fragment_layout,omitempty"`
}

func (x *ControllerMessage_FragLayoutResponse) Reset() {
	*x = ControllerMessage_FragLayoutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_client_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControllerMessage_FragLayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage_FragLayoutResponse) ProtoMessage() {}

func (x *ControllerMessage_FragLayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_client_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage_FragLayoutResponse.ProtoReflect.Descriptor instead.
func (*ControllerMessage_FragLayoutResponse) Descriptor() ([]byte, []int) {
	return file_controller_client_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ControllerMessage_FragLayoutResponse) GetStatusCode() ControllerMessage_StatusCode {
	if x != nil {
		return x.StatusCode
	}
	return ControllerMessage_OK
}

func (x *ControllerMessage_FragLayoutResponse) GetTotalNumFragments() uint32 {
	if x != nil {
		return x.TotalNumFragments
	}
	return 0
}

func (x *ControllerMessage_FragLayoutResponse) GetFragmentLayout() []*ControllerMessage_FragLayoutResponse_FragmentInfo {
	if x != nil {
		return x.FragmentLayout
	}
	return nil
}

type ControllerMessage_DeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode ControllerMessage_StatusCode `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=ControllerMessage_StatusCode" json:"status_code,omitempty"`
}

func (x *ControllerMessage_DeleteResponse) Reset() {
	*x = ControllerMessage_DeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_client_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControllerMessage_DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage_DeleteResponse) ProtoMessage() {}

func (x *ControllerMessage_DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_client_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage_DeleteResponse.ProtoReflect.Descriptor instead.
func (*ControllerMessage_DeleteResponse) Descriptor() ([]byte, []int) {
	return file_controller_client_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ControllerMessage_DeleteResponse) GetStatusCode() ControllerMessage_StatusCode {
	if x != nil {
		return x.StatusCode
	}
	return ControllerMessage_OK
}

type ControllerMessage_LsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode  ControllerMessage_StatusCode             `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=ControllerMessage_StatusCode" json:"status_code,omitempty"`
	ActiveNodes []*ControllerMessage_LsResponse_NodeInfo `protobuf:"bytes,2,rep,name=active_nodes,json=activeNodes,proto3" json:"active_nodes,omitempty"`
}

func (x *ControllerMessage_LsResponse) Reset() {
	*x = ControllerMessage_LsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_client_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControllerMessage_LsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage_LsResponse) ProtoMessage() {}

func (x *ControllerMessage_LsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_client_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage_LsResponse.ProtoReflect.Descriptor instead.
func (*ControllerMessage_LsResponse) Descriptor() ([]byte, []int) {
	return file_controller_client_proto_rawDescGZIP(), []int{0, 3}
}

func (x *ControllerMessage_LsResponse) GetStatusCode() ControllerMessage_StatusCode {
	if x != nil {
		return x.StatusCode
	}
	return ControllerMessage_OK
}

func (x *ControllerMessage_LsResponse) GetActiveNodes() []*ControllerMessage_LsResponse_NodeInfo {
	if x != nil {
		return x.ActiveNodes
	}
	return nil
}

type ControllerMessage_PlanResponse_StorageNodeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StorageNodeId string `protobuf:"bytes,1,opt,name=storage_node_id,json=storageNodeId,proto3" json:"storage_node_id,omitempty"`
	Host          string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          string `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *ControllerMessage_PlanResponse_StorageNodeInfo) Reset() {
	*x = ControllerMessage_PlanResponse_StorageNodeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_client_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControllerMessage_PlanResponse_StorageNodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage_PlanResponse_StorageNodeInfo) ProtoMessage() {}

func (x *ControllerMessage_PlanResponse_StorageNodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_controller_client_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage_PlanResponse_StorageNodeInfo.ProtoReflect.Descriptor instead.
func (*ControllerMessage_PlanResponse_StorageNodeInfo) Descriptor() ([]byte, []int) {
	return file_controller_client_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ControllerMessage_PlanResponse_StorageNodeInfo) GetStorageNodeId() string {
	if x != nil {
		return x.StorageNodeId
	}
	return ""
}

func (x *ControllerMessage_PlanResponse_StorageNodeInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ControllerMessage_PlanResponse_StorageNodeInfo) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type ControllerMessage_PlanResponse_FragmentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FragmentId     string                                            `protobuf:"bytes,1,opt,name=fragment_id,json=fragmentId,proto3" json:"fragment_id,omitempty"`
	Size           int64                                             `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	StorageNodeIds []*ControllerMessage_PlanResponse_StorageNodeInfo `protobuf:"bytes,3,rep,name=storage_node_ids,json=storageNodeIds,proto3" json:"storage_node_ids,omitempty"`
}

func (x *ControllerMessage_PlanResponse_FragmentInfo) Reset() {
	*x = ControllerMessage_PlanResponse_FragmentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_client_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControllerMessage_PlanResponse_FragmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage_PlanResponse_FragmentInfo) ProtoMessage() {}

func (x *ControllerMessage_PlanResponse_FragmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_controller_client_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage_PlanResponse_FragmentInfo.ProtoReflect.Descriptor instead.
func (*ControllerMessage_PlanResponse_FragmentInfo) Descriptor() ([]byte, []int) {
	return file_controller_client_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *ControllerMessage_PlanResponse_FragmentInfo) GetFragmentId() string {
	if x != nil {
		return x.FragmentId
	}
	return ""
}

func (x *ControllerMessage_PlanResponse_FragmentInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ControllerMessage_PlanResponse_FragmentInfo) GetStorageNodeIds() []*ControllerMessage_PlanResponse_StorageNodeInfo {
	if x != nil {
		return x.StorageNodeIds
	}
	return nil
}

type ControllerMessage_FragLayoutResponse_StorageNodeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StorageNodeId string `protobuf:"bytes,1,opt,name=storage_node_id,json=storageNodeId,proto3" json:"storage_node_id,omitempty"`
	Host          string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          string `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *ControllerMessage_FragLayoutResponse_StorageNodeInfo) Reset() {
	*x = ControllerMessage_FragLayoutResponse_StorageNodeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_client_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControllerMessage_FragLayoutResponse_StorageNodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage_FragLayoutResponse_StorageNodeInfo) ProtoMessage() {}

func (x *ControllerMessage_FragLayoutResponse_StorageNodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_controller_client_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage_FragLayoutResponse_StorageNodeInfo.ProtoReflect.Descriptor instead.
func (*ControllerMessage_FragLayoutResponse_StorageNodeInfo) Descriptor() ([]byte, []int) {
	return file_controller_client_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *ControllerMessage_FragLayoutResponse_StorageNodeInfo) GetStorageNodeId() string {
	if x != nil {
		return x.StorageNodeId
	}
	return ""
}

func (x *ControllerMessage_FragLayoutResponse_StorageNodeInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ControllerMessage_FragLayoutResponse_StorageNodeInfo) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type ControllerMessage_FragLayoutResponse_FragmentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FragmentId     string                                                  `protobuf:"bytes,1,opt,name=fragment_id,json=fragmentId,proto3" json:"fragment_id,omitempty"`
	Size           int64                                                   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	StorageNodeIds []*ControllerMessage_FragLayoutResponse_StorageNodeInfo `protobuf:"bytes,3,rep,name=storage_node_ids,json=storageNodeIds,proto3" json:"storage_node_ids,omitempty"`
}

func (x *ControllerMessage_FragLayoutResponse_FragmentInfo) Reset() {
	*x = ControllerMessage_FragLayoutResponse_FragmentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_client_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControllerMessage_FragLayoutResponse_FragmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage_FragLayoutResponse_FragmentInfo) ProtoMessage() {}

func (x *ControllerMessage_FragLayoutResponse_FragmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_controller_client_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage_FragLayoutResponse_FragmentInfo.ProtoReflect.Descriptor instead.
func (*ControllerMessage_FragLayoutResponse_FragmentInfo) Descriptor() ([]byte, []int) {
	return file_controller_client_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *ControllerMessage_FragLayoutResponse_FragmentInfo) GetFragmentId() string {
	if x != nil {
		return x.FragmentId
	}
	return ""
}

func (x *ControllerMessage_FragLayoutResponse_FragmentInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ControllerMessage_FragLayoutResponse_FragmentInfo) GetStorageNodeIds() []*ControllerMessage_FragLayoutResponse_StorageNodeInfo {
	if x != nil {
		return x.StorageNodeIds
	}
	return nil
}

type ControllerMessage_LsResponse_NodeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId             string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	DiskSpace          int64  `protobuf:"varint,2,opt,name=disk_space,json=diskSpace,proto3" json:"disk_space,omitempty"`
	NumRequestsHandled int64  `protobuf:"varint,3,opt,name=num_requests_handled,json=numRequestsHandled,proto3" json:"num_requests_handled,omitempty"`
}

func (x *ControllerMessage_LsResponse_NodeInfo) Reset() {
	*x = ControllerMessage_LsResponse_NodeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_client_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControllerMessage_LsResponse_NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage_LsResponse_NodeInfo) ProtoMessage() {}

func (x *ControllerMessage_LsResponse_NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_controller_client_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage_LsResponse_NodeInfo.ProtoReflect.Descriptor instead.
func (*ControllerMessage_LsResponse_NodeInfo) Descriptor() ([]byte, []int) {
	return file_controller_client_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *ControllerMessage_LsResponse_NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ControllerMessage_LsResponse_NodeInfo) GetDiskSpace() int64 {
	if x != nil {
		return x.DiskSpace
	}
	return 0
}

func (x *ControllerMessage_LsResponse_NodeInfo) GetNumRequestsHandled() int64 {
	if x != nil {
		return x.NumRequestsHandled
	}
	return 0
}

type ClientMessage_PutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RestOption        ClientMessage_RestOption `protobuf:"varint,1,opt,name=rest_option,json=restOption,proto3,enum=ClientMessage_RestOption" json:"rest_option,omitempty"`
	Filename          string                   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Filesize          int64                    `protobuf:"varint,3,opt,name=filesize,proto3" json:"filesize,omitempty"`
	OptionalChunkSize int64                    `protobuf:"varint,4,opt,name=optional_chunk_size,json=optionalChunkSize,proto3" json:"optional_chunk_size,omitempty"`
}

func (x *ClientMessage_PutRequest) Reset() {
	*x = ClientMessage_PutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_client_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_PutRequest) ProtoMessage() {}

func (x *ClientMessage_PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_client_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_PutRequest.ProtoReflect.Descriptor instead.
func (*ClientMessage_PutRequest) Descriptor() ([]byte, []int) {
	return file_controller_client_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ClientMessage_PutRequest) GetRestOption() ClientMessage_RestOption {
	if x != nil {
		return x.RestOption
	}
	return ClientMessage_GET
}

func (x *ClientMessage_PutRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ClientMessage_PutRequest) GetFilesize() int64 {
	if x != nil {
		return x.Filesize
	}
	return 0
}

func (x *ClientMessage_PutRequest) GetOptionalChunkSize() int64 {
	if x != nil {
		return x.OptionalChunkSize
	}
	return 0
}

type ClientMessage_GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RestOption ClientMessage_RestOption `protobuf:"varint,1,opt,name=rest_option,json=restOption,proto3,enum=ClientMessage_RestOption" json:"rest_option,omitempty"`
	FileName   string                   `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *ClientMessage_GetRequest) Reset() {
	*x = ClientMessage_GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_client_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_GetRequest) ProtoMessage() {}

func (x *ClientMessage_GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_client_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_GetRequest.ProtoReflect.Descriptor instead.
func (*ClientMessage_GetRequest) Descriptor() ([]byte, []int) {
	return file_controller_client_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ClientMessage_GetRequest) GetRestOption() ClientMessage_RestOption {
	if x != nil {
		return x.RestOption
	}
	return ClientMessage_GET
}

func (x *ClientMessage_GetRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type ClientMessage_DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RestOption ClientMessage_RestOption `protobuf:"varint,1,opt,name=rest_option,json=restOption,proto3,enum=ClientMessage_RestOption" json:"rest_option,omitempty"`
	Filename   string                   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *ClientMessage_DeleteRequest) Reset() {
	*x = ClientMessage_DeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_client_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_DeleteRequest) ProtoMessage() {}

func (x *ClientMessage_DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_client_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_DeleteRequest.ProtoReflect.Descriptor instead.
func (*ClientMessage_DeleteRequest) Descriptor() ([]byte, []int) {
	return file_controller_client_proto_rawDescGZIP(), []int{1, 2}
}

func (x *ClientMessage_DeleteRequest) GetRestOption() ClientMessage_RestOption {
	if x != nil {
		return x.RestOption
	}
	return ClientMessage_GET
}

func (x *ClientMessage_DeleteRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type ClientMessage_LsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RestOption ClientMessage_RestOption `protobuf:"varint,1,opt,name=rest_option,json=restOption,proto3,enum=ClientMessage_RestOption" json:"rest_option,omitempty"`
}

func (x *ClientMessage_LsRequest) Reset() {
	*x = ClientMessage_LsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_client_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_LsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_LsRequest) ProtoMessage() {}

func (x *ClientMessage_LsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_client_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_LsRequest.ProtoReflect.Descriptor instead.
func (*ClientMessage_LsRequest) Descriptor() ([]byte, []int) {
	return file_controller_client_proto_rawDescGZIP(), []int{1, 3}
}

func (x *ClientMessage_LsRequest) GetRestOption() ClientMessage_RestOption {
	if x != nil {
		return x.RestOption
	}
	return ClientMessage_GET
}

var File_controller_client_proto protoreflect.FileDescriptor

var file_controller_client_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xea, 0x0d, 0x0a, 0x11, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x46, 0x0a, 0x0d, 0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x14, 0x66, 0x72, 0x61, 0x67, 0x5f,
	0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x46, 0x72, 0x61, 0x67, 0x4c, 0x61,
	0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x12,
	0x66, 0x72, 0x61, 0x67, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00,
	0x52, 0x0e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x40, 0x0a, 0x0b, 0x6c, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x1a, 0xd9, 0x03, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6e, 0x75, 0x6d,
	0x5f, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x11, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x55, 0x0a, 0x0f, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x5f,
	0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x72,
	0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x66, 0x72, 0x61, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x1a, 0x61, 0x0a, 0x0f, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a,
	0x0f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x1a, 0x9e, 0x01,
	0x0a, 0x0c, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f,
	0x0a, 0x0b, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x12, 0x59, 0x0a, 0x10, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x73, 0x1a, 0xeb,
	0x03, 0x0a, 0x12, 0x46, 0x72, 0x61, 0x67, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6e,
	0x75, 0x6d, 0x5f, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x11, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x46, 0x72, 0x61, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x5b, 0x0a, 0x0f, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x32,
	0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x46, 0x72, 0x61, 0x67, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0e, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0x1a, 0x61, 0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x1a, 0xa4, 0x01, 0x0a, 0x0c, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x72, 0x61,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x5f, 0x0a, 0x10, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x46, 0x72, 0x61, 0x67, 0x4c, 0x61,
	0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x73, 0x1a, 0x50, 0x0a, 0x0e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e,
	0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x1a, 0x8d,
	0x02, 0x0a, 0x0a, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a,
	0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x49, 0x0a,
	0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x1a, 0x74, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x64, 0x69, 0x73, 0x6b, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x14,
	0x6e, 0x75, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x5f, 0x68, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x6e, 0x75, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x64, 0x22, 0x60,
	0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x06, 0x0a, 0x02,
	0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12,
	0x12, 0x0a, 0x0e, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e,
	0x44, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x41, 0x4c, 0x52, 0x45,
	0x41, 0x44, 0x59, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x53, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e,
	0x46, 0x49, 0x4c, 0x45, 0x5f, 0x54, 0x4f, 0x4f, 0x5f, 0x4c, 0x41, 0x52, 0x47, 0x45, 0x10, 0x04,
	0x42, 0x14, 0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x9f, 0x06, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3c, 0x0a, 0x0b, 0x70, 0x75, 0x74, 0x5f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x75,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x70, 0x75, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0b, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x67, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x45, 0x0a, 0x0e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x6c,
	0x73, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x4c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0xb0, 0x01, 0x0a, 0x0a, 0x50, 0x75, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x74, 0x5f, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x1a, 0x65, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x74, 0x5f,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x73,
	0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x74, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x1a, 0x67, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x3a, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x47, 0x0a, 0x09, 0x4c, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x74, 0x5f, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x74,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x32, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x07, 0x0a, 0x03, 0x47, 0x45, 0x54, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x55, 0x54,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x12, 0x06,
	0x0a, 0x02, 0x4c, 0x53, 0x10, 0x03, 0x42, 0x10, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x1e, 0x5a, 0x1c, 0x2e, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_controller_client_proto_rawDescOnce sync.Once
	file_controller_client_proto_rawDescData = file_controller_client_proto_rawDesc
)

func file_controller_client_proto_rawDescGZIP() []byte {
	file_controller_client_proto_rawDescOnce.Do(func() {
		file_controller_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_controller_client_proto_rawDescData)
	})
	return file_controller_client_proto_rawDescData
}

var file_controller_client_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_controller_client_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_controller_client_proto_goTypes = []interface{}{
	(ControllerMessage_StatusCode)(0),                            // 0: ControllerMessage.StatusCode
	(ClientMessage_RestOption)(0),                                // 1: ClientMessage.RestOption
	(*ControllerMessage)(nil),                                    // 2: ControllerMessage
	(*ClientMessage)(nil),                                        // 3: ClientMessage
	(*ControllerMessage_PlanResponse)(nil),                       // 4: ControllerMessage.PlanResponse
	(*ControllerMessage_FragLayoutResponse)(nil),                 // 5: ControllerMessage.FragLayoutResponse
	(*ControllerMessage_DeleteResponse)(nil),                     // 6: ControllerMessage.DeleteResponse
	(*ControllerMessage_LsResponse)(nil),                         // 7: ControllerMessage.LsResponse
	(*ControllerMessage_PlanResponse_StorageNodeInfo)(nil),       // 8: ControllerMessage.PlanResponse.StorageNodeInfo
	(*ControllerMessage_PlanResponse_FragmentInfo)(nil),          // 9: ControllerMessage.PlanResponse.FragmentInfo
	(*ControllerMessage_FragLayoutResponse_StorageNodeInfo)(nil), // 10: ControllerMessage.FragLayoutResponse.StorageNodeInfo
	(*ControllerMessage_FragLayoutResponse_FragmentInfo)(nil),    // 11: ControllerMessage.FragLayoutResponse.FragmentInfo
	(*ControllerMessage_LsResponse_NodeInfo)(nil),                // 12: ControllerMessage.LsResponse.NodeInfo
	(*ClientMessage_PutRequest)(nil),                             // 13: ClientMessage.PutRequest
	(*ClientMessage_GetRequest)(nil),                             // 14: ClientMessage.GetRequest
	(*ClientMessage_DeleteRequest)(nil),                          // 15: ClientMessage.DeleteRequest
	(*ClientMessage_LsRequest)(nil),                              // 16: ClientMessage.LsRequest
}
var file_controller_client_proto_depIdxs = []int32{
	4,  // 0: ControllerMessage.plan_response:type_name -> ControllerMessage.PlanResponse
	5,  // 1: ControllerMessage.frag_layout_response:type_name -> ControllerMessage.FragLayoutResponse
	6,  // 2: ControllerMessage.delete_response:type_name -> ControllerMessage.DeleteResponse
	7,  // 3: ControllerMessage.ls_response:type_name -> ControllerMessage.LsResponse
	13, // 4: ClientMessage.put_request:type_name -> ClientMessage.PutRequest
	14, // 5: ClientMessage.get_request:type_name -> ClientMessage.GetRequest
	15, // 6: ClientMessage.delete_request:type_name -> ClientMessage.DeleteRequest
	16, // 7: ClientMessage.ls_request:type_name -> ClientMessage.LsRequest
	0,  // 8: ControllerMessage.PlanResponse.status_code:type_name -> ControllerMessage.StatusCode
	9,  // 9: ControllerMessage.PlanResponse.fragment_layout:type_name -> ControllerMessage.PlanResponse.FragmentInfo
	0,  // 10: ControllerMessage.FragLayoutResponse.status_code:type_name -> ControllerMessage.StatusCode
	11, // 11: ControllerMessage.FragLayoutResponse.fragment_layout:type_name -> ControllerMessage.FragLayoutResponse.FragmentInfo
	0,  // 12: ControllerMessage.DeleteResponse.status_code:type_name -> ControllerMessage.StatusCode
	0,  // 13: ControllerMessage.LsResponse.status_code:type_name -> ControllerMessage.StatusCode
	12, // 14: ControllerMessage.LsResponse.active_nodes:type_name -> ControllerMessage.LsResponse.NodeInfo
	8,  // 15: ControllerMessage.PlanResponse.FragmentInfo.storage_node_ids:type_name -> ControllerMessage.PlanResponse.StorageNodeInfo
	10, // 16: ControllerMessage.FragLayoutResponse.FragmentInfo.storage_node_ids:type_name -> ControllerMessage.FragLayoutResponse.StorageNodeInfo
	1,  // 17: ClientMessage.PutRequest.rest_option:type_name -> ClientMessage.RestOption
	1,  // 18: ClientMessage.GetRequest.rest_option:type_name -> ClientMessage.RestOption
	1,  // 19: ClientMessage.DeleteRequest.rest_option:type_name -> ClientMessage.RestOption
	1,  // 20: ClientMessage.LsRequest.rest_option:type_name -> ClientMessage.RestOption
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_controller_client_proto_init() }
func file_controller_client_proto_init() {
	if File_controller_client_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_controller_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControllerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_client_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControllerMessage_PlanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_client_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControllerMessage_FragLayoutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_client_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControllerMessage_DeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_client_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControllerMessage_LsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_client_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControllerMessage_PlanResponse_StorageNodeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_client_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControllerMessage_PlanResponse_FragmentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_client_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControllerMessage_FragLayoutResponse_StorageNodeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_client_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControllerMessage_FragLayoutResponse_FragmentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_client_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControllerMessage_LsResponse_NodeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_client_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_PutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_client_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_client_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_DeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_client_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_LsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_controller_client_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ControllerMessage_PlanResponse_)(nil),
		(*ControllerMessage_FragLayoutResponse_)(nil),
		(*ControllerMessage_DeleteResponse_)(nil),
		(*ControllerMessage_LsResponse_)(nil),
	}
	file_controller_client_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ClientMessage_PutRequest_)(nil),
		(*ClientMessage_GetRequest_)(nil),
		(*ClientMessage_DeleteRequest_)(nil),
		(*ClientMessage_LsRequest_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_controller_client_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controller_client_proto_goTypes,
		DependencyIndexes: file_controller_client_proto_depIdxs,
		EnumInfos:         file_controller_client_proto_enumTypes,
		MessageInfos:      file_controller_client_proto_msgTypes,
	}.Build()
	File_controller_client_proto = out.File
	file_controller_client_proto_rawDesc = nil
	file_controller_client_proto_goTypes = nil
	file_controller_client_proto_depIdxs = nil
}
